apiVersion: v1
data:
  alertmanager.yml: |
    global:
      slack_api_url: https://hooks.slack.com/services/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
    receivers:
    - name: slack-notifier
      slack_configs:
      - channel: ['#monitoring-info', 'k8s-monitoring']
        send_resolved: true
        title: "Summary: {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "Description: {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

    route:
      group_interval: 1m
      group_wait: 10s
      receiver: slack-notifier
      repeat_interval: 2m
  allow-snippet-annotations: "false"
