apiVersion: v1
data:
  alertmanager.yml: |
    global:
      slack_api_url: https://hooks.slack.com/services/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
    receivers:
    - name: k8s-monitoring
      slack_configs:
      - channel: '#k8s-monitoring'
        send_resolved: true
        text: |-
          Description: {{ range .Alerts }}{{ .Annotations.description }}
          {{ end }}
        title: |-
          Summary: {{ range .Alerts }}{{ .Annotations.summary }}
          {{ end }}
    - name: slack-info
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#monitoring-info'
        send_resolved: true
        text: |-
          Description: {{ range .Alerts }}{{ .Annotations.description }}'
          {{ end }}
        title: |-
          Summary: {{ range .Alerts }}{{ .Annotations.summary }}
          {{ end }}
    - name: slack-warning
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#monitoring-warning'
        send_resolved: true
        text: |-
          Description: {{ range .Alerts }}{{ .Annotations.description }}
          {{ end }}
        title: |-
          Summary: {{ range .Alerts }}{{ .Annotations.summary }}
          {{ end }}
    - name: slack-error
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#monitoring-error'
        send_resolved: true
        text: |-
          Description: {{ range .Alerts }}{{ .Annotations.description }}
          {{ end }}
        title: |-
          Summary: {{ range .Alerts }}{{ .Annotations.summary }}
          {{ end }}
    route:
      receiver: k8s-monitoring
      group_interval: 1m
      group_wait: 10s
      repeat_interval: 1m
      routes:
      - receiver: slack-info
        matchers:
        - severity = "info"
      - receiver: slack-warning
        matchers:
        - severity = "page"
      - receiver: slack-error
        matchers:
        - severity = "critical"


  allow-snippet-annotations: "false"
  
---

apiVersion: v1
data:
  alertmanager.yml: "global:\n  slack_api_url: https://hooks.slack.com/services/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\nreceivers:\n-
    name: k8s-monitoring\n  slack_configs:\n  - channel: '#k8s-monitoring'\n    send_resolved:
    true\n    text: |-\n      Description: {{ range .Alerts }}{{ .Annotations.description
    }}\n      {{ end }}\n    title: |-\n      Summary: {{ range .Alerts }}{{ .Annotations.summary
    }}\n      {{ end }}\n- name: slack-info\n  slack_configs:\n  - api_url: https://hooks.slack.com/services/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\n
    \   channel: '#monitoring-info'\n    send_resolved: true\n    text: |-\n      Description:
    {{ range .Alerts }}{{ .Annotations.description }}'\n      {{ end }}\n    title:
    |-\n      Summary: {{ range .Alerts }}{{ .Annotations.summary }}\n      {{ end
    }}\n- name: slack-warning\n  slack_configs:\n  - api_url: https://hooks.slack.com/services/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\n
    \   channel: '#monitoring-warning'\n    send_resolved: true\n    text: |-\n      Description:
    {{ range .Alerts }}{{ .Annotations.description }}\n      {{ end }}\n    title:
    |-\n      Summary: {{ range .Alerts }}{{ .Annotations.summary }}\n      {{ end
    }}\n- name: slack-error\n  slack_configs:\n  - api_url: https://hooks.slack.com/services/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\n
    \   channel: '#monitoring-error'\n    send_resolved: true\n    text: |-\n      Description:
    {{ range .Alerts }}{{ .Annotations.description }}\n      {{ end }}\n    title:
    |-\n      Summary: {{ range .Alerts }}{{ .Annotations.summary }}\n      {{ end
    }}\nroute:\n  receiver: k8s-monitoring\n  group_interval: 1m\n  group_wait: 10s\n
    \ repeat_interval: 3m\n  routes:\n  - receiver: slack-info\n    matchers:\n    -
    severity = \"info\"\n  - receiver: slack-warning \n    matchers:\n    - severity
    = \"page\"\n  - receiver: slack-error\n    matchers:\n    - severity = \"critical\"\n"

  allow-snippet-annotations: "false"

