  alerting_rules.yml: |
    groups:
    - name: AllInstances
      rules:
      - alert: InstanceDown
        annotations:
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
            for more than 1 minute.'
          summary: Instance {{ $labels.instance }} down
        expr: up == 0
        for: 1m
        labels:
          severity: "info"
      - alert: InstanceScaleOut
        annotations:
          description: Cluster has been scale out 1 node for more than 10 seconds.
          summary: Instance {{ $labels.instance }} scale out
        expr: (sum(kube_node_info) > sum(kube_node_info offset 1m))
        for: 10s
        labels:
          severity: "info"
      - alert: ZoneA
        annotations:
          description: 'Zone A has only one node. Perhaps zone a has no worker nodes.'
          summary: {{ $labels.topology_kubernetes_io_region }} needs check
        expr: sum(up{topology_kubernetes_io_zone=~"ap-northeast-3a"} and up{job="kubernetes-nodes"}) < 3
        for: 1m
        labels:
          severity: "warning"
      - alert: ZoneB
        annotations:
          description: 'Zone B has only one node. Perhaps zone b has no worker nodes.'
          summary: {{ $labels.topology_kubernetes_io_region }} needs check
        expr: sum(up{topology_kubernetes_io_zone=~"ap-northeast-3b"} and up{job="kubernetes-nodes"}) == 1
        for: 1m
        labels:
          severity: "warning"
      - alert: ZoneC
        annotations:
          description: 'Zone C has only one node. Perhaps zone a has no worker nodes.'
          summary: {{ $labels.topology_kubernetes_io_region }} needs check
        expr: sum(up{topology_kubernetes_io_zone=~"ap-northeast-3c"} and up{job="kubernetes-nodes"}) == 1
        for: 1m
        labels:
          severity: "warning"
---

apiVersion: v1
data:
  alerting_rules.yml: "groups:\n- name: AllInstances\n  rules:\n  - alert: ComponentDown\n
    \   annotations:\n      description: '{{ $labels.instance }} of job {{ $labels.job
    }} has been down\n        for more than 1 minute.'\n      summary: Job {{ $labels.job
    }} down\n    expr: up == 0\n    for: 1m\n    labels:\n      severity: \"info\"\n
    \ - alert: InstanceScaleOut\n    annotations:\n      description: Cluster has
    been scale out 1 node for more than 10 seconds.\n      summary: Instance {{ $labels.instance
    }} scale out\n    expr: (sum(kube_node_info) > sum(kube_node_info offset 1m))\n
    \   for: 10s\n    labels:\n      severity: \"info\"\n  - alert: ZoneA\n    annotations:\n
    \     description: Zone A has only 1 node. Perhaps zone A has no worker nodes.\n
    \     summary: needs check\n    expr: sum(up{topology_kubernetes_io_zone=~\"ap-northeast-3a\"}
    and up{job=\"kubernetes-nodes\"}) == 1    \n    for: 1m\n    labels:\n      severity:
    \"page\"\n  - alert: ZoneB\n    annotations:\n      description: Zone B has only
    1 node. Perhaps zone b has no worker nodes.\n      summary: needs check\n    expr:
    sum(up{topology_kubernetes_io_zone=~\"ap-northeast-3b\"} and up{job=\"kubernetes-nodes\"})
    == 1    \n    for: 1m\n    labels:\n      severity: \"page\"\n  - alert: ZoneC\n
    \   annotations:\n      description: Zone C has only 1 node. Perhaps zone b has
    no worker nodes.\n      summary: needs check\n    expr: sum(up{topology_kubernetes_io_zone=~\"ap-northeast-3c\"}
    and up{job=\"kubernetes-nodes\"}) == 1    \n    for: 1m\n    labels:\n      severity:
    \"page\"\n  - alert: MasterDown\n    annotations:\n      description: Master node
    down.\n      summary: needs check\n    expr: sum(up{key=\"master\"} and up{job=\"kubernetes-nodes\"})
    < 3    \n    for: 1m\n    labels:\n      severity: \"critical\"\n  - alert: NodeBusy\n
    \   annotations:\n      description: Many Instance scale out.\n      summary:
    3 nodes scale out\n    expr: sum(up{job=\"kubernetes-nodes\"}) > 11    \n    for:
    1m\n    labels:\n      severity: \"info\"\n"
