apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch1
spec:
  storageClassName: "elasticsearch"
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: [Filesystem ID]
