{
 "title": "For Demo video",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "CPU usage AVG(%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(100 -  (irate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http request per pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{status=\"200\", job!=\"my-flask-app\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio of nodes by AZ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{topology_kubernetes_io_zone=~\"ap-northeast-3a\"} and up{job=\"kubernetes-nodes\"})",
     "legendFormat": "Zone A"
    },
    {
     "expr": "sum(sum(up{topology_kubernetes_io_zone=~\"ap-northeast-3b\"} and up{job=\"kubernetes-nodes\"}))",
     "legendFormat": "Zone B"
    },
    {
     "expr": "sum(up{topology_kubernetes_io_zone=~\"ap-northeast-3c\"} and up{job=\"kubernetes-nodes\"})",
     "legendFormat": "Zone C"
    }
   ]
  },
  {
   "title": "All Instance num",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{key!=\"master\"} and up{job=\"kubernetes-nodes\"})",
     "legendFormat": "Worker"
    },
    {
     "expr": "sum(up{key=\"master\"} and up{job=\"kubernetes-nodes\"})",
     "legendFormat": "Master"
    },
    { "expr": "sum(flask_exporter_info{}) -1", "legendFormat": "Pod-flask" }
   ]
  },
  {
   "title": "Total node Memory Usage avg(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes ) * 100)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Total Http request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{status=\"200\"}[1m])  ",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(flask_http_request_total{status!=\"200\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver request latency",
   "type": "graph",
   "description": "95th percentile request latency for Kubernetes apiserver component",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p50 "
    }
   ]
  }
 ]
}